# Generated by Django 5.2 on 2025-04-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='N_Banos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='N_Camas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='N_Personas',
            field=models.IntegerField(default=1),
        ),
    ]
