# Generated by Django 5.2 on 2025-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_n_banos_apartment_n_camas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='ImagePath',
            field=models.TextField(blank=True, null=True),
        ),
    ]
