# Generated by Django 5.2 on 2025-05-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_amenity_apartmentnew_apartmentpicture_room_bed_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amenity',
            table='amenities',
        ),
        migrations.AlterModelTable(
            name='apartmentamenity',
            table='apartment_amenities',
        ),
        migrations.AlterModelTable(
            name='apartmentnew',
            table='apartments_new',
        ),
        migrations.AlterModelTable(
            name='apartmentpicture',
            table='pictures',
        ),
        migrations.AlterModelTable(
            name='bed',
            table='beds',
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
    ]
