# Generated by Django 5.2 on 2025-05-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_alter_amenity_table_alter_apartmentamenity_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amenity',
            table='apartments_amenities',
        ),
        migrations.AlterModelTable(
            name='apartmentamenity',
            table='apartments_apartment_amenities',
        ),
        migrations.AlterModelTable(
            name='apartmentpicture',
            table='apartments_pictures',
        ),
        migrations.AlterModelTable(
            name='bed',
            table='apartments_beds',
        ),
        migrations.AlterModelTable(
            name='room',
            table='apartments_rooms',
        ),
    ]
