# Generated by Django 5.2 on 2025-05-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_alter_amenity_table_alter_apartmentamenity_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apartmentnew',
            table='apartments_apartmentnew',
        ),
    ]
