# Generated by Django 5.2 on 2025-05-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_alter_apartmentnew_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentnew',
            old_name='county',
            new_name='country',
        ),
    ]
