# Generated by Django 5.2 on 2025-05-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_apartmentcountry_apartmentcity_apartmentneighborhood'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apartmentcity',
            table='apartment_cities',
        ),
        migrations.AlterModelTable(
            name='apartmentcountry',
            table='apartment_countries',
        ),
        migrations.AlterModelTable(
            name='apartmentneighborhood',
            table='apartment_neighborhoods',
        ),
    ]
