# Generated by Django 5.2 on 2025-05-09 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_rename_county_apartmentnew_country'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservation', to='apartments.apartment'),
        ),
        migrations.CreateModel(
            name='ReservationNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_new', to='apartments.apartmentnew')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservations_new', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
