# Generated by Django 5.2 on 2025-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_apartment_reservationnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationnew',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservationnew',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservationnew',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservationnew',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservationnew',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
